### ISSUE TITLE
build logs appear to be blocked

### ISSUE THREAD

**Issue by brenton** [openshift/training#33]
We'll probably have to track this as a BZ if we actually need a code change:

```
osc build-logs sin-89d70fac-c2b1-11e4-b853-525400b33d1d
Forbidden: "/osapi/v1beta1/redirect/buildLogs/sin-89d70fac-c2b1-11e4-853-525400b33d1d?namespace=sinatra" denied by default
```

**Comment by brenton** [comment]
@deads2k, is this a known issue by any chance?  I didn't see anything filed in origin.

**Comment by deads2k** [comment]
No, not known.

**Comment by deads2k** [comment]
This will need a code change to update the default policy.  Simple access is easy, but deciding exactly how to handle `redirect` is not.  I'll get it out of the ditch, but the fix may need revisiting as we secure the nodes.

**Comment by thoraxe** [comment]
Is there a BZ to track this? This is a blocker for beta2, otherwise @deads2k  you need to document the workaround.

**Comment by deads2k** [comment]
fixed by: https://github.com/openshift/origin/pull/1238

**Comment by sdodson** [comment]
This has been pulled into openshift-0.4-0.git.43.e57c9a8.el7ose

**Comment by sdodson** [comment]
I'm still getting the same error with the patch applied, does this depend on anything else since v0.4 was tagged?

```
[joe@ose3-master ~]$ osc build-logs sin-731a45d1-c450-11e4-a046-fa163ee3cea0
Forbidden: "/osapi/v1beta1/redirect/buildLogs/sin-731a45d1-c450-11e4-a046-fa163ee3cea0?namespace=sinatra" denied by default

[joe@ose3-master ~]$ openshift version
openshift v0.4-41-ge57c9a8
kubernetes v0.10.0-503-gc977a45

$ git log e57c9a8 -n 1
commit e57c9a8da090fde3dce3cc9558560e85ee9809ad
Author: deads2k <deads@redhat.com>
Date:   Thu Mar 5 15:03:34 2015 -0500

    add redirect to list of approved verbs
```

**Comment by deads2k** [comment]
Did you start from a new or existing etcd?  Changes to bootstrap policy only take effect if you launch with a clean etcd.  We're working on changing that, but it will be too big to backport.

**Comment by sdodson** [comment]
I just updated the binary and restarted. I'll start fresh now. Thanks.

**Comment by thoraxe** [comment]
I did not see this forbidden error this morning, so I'm closing.
